# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
lane :codecoverage do
scan(
workspace: "SPHTech.xcworkspace",
scheme: "SPHTech",
output_directory: "fastlane/test_output/",
clean: true,
code_coverage: true,
device: "iPhone 8 Plus",
output_types: "html"
)
sh "slather coverage --ignore '../../*' \
--html \
--scheme SPHTech \
--workspace ../SPHTech.xcworkspace \
--output-directory test_output/code_coverage/ \
../SPHTech.xcodeproj"
end
end

