version: 2
jobs:
  build:

    macos:
      xcode: "10.1"

    steps:
      - checkout
       # Install CocoaPods
      - run:
          name: Install CocoaPods
          paths: SPHTech
          command: cd SPHTech |
            pod install
      - run:
          name: Build and run tests
          command: fastlane scan